### PR TITLE
fif: Fix missing fzf option --preview-window

### PR DESCRIPTION
**Pull request by gerardbosch**
Signed-off-by: Gerard Bosch <gerard.bosch@gmail.com>

# License Acceptance

- [x] This repository is Apache version 2.0 licensed (some scripts may have alternate licensing inline in their code) and by making this PR, I am contributing my changes to the repository under the terms of the Apache 2 license.

### CODE REVIEW

**Comment by gerardbosch** [comment]
I fixed the Markdown linter complain that made the pipeline to fail in #59 :)

**Review by unixorn — CHANGES_REQUESTED** [review]
I think people might get annoyed if we stuff in an editorconfig and their editor changes theri settings out from under them. Let's discuss that in a separate issue so we can merge the other changes.

Thanks!

**Comment by gerardbosch** [comment]
> I think people might get annoyed if we stuff in an editorconfig and their editor changes theri settings out from under them. Let's discuss that in a separate issue so we can merge the other changes.
> 
> Thanks!

Sure, no problem! I will remove the .editorconfig then. I just thought it would be good to keep the consistency across the scripts as they will potentially be added and modified by different people with different settings for indentation for example. What usually leads to very inconsistent mixture of tabs, spaces and stuff in the same project and even same file.

**Comment by unixorn** [comment]
Thanks for the contribution!

**Pull request merged**
