### PR TITLE
Custom fzf install directory

### PR DESCRIPTION
**Pull request by caojoshua**
# Description

Allows user to specify a custom fzf install directory. By default, it is still installed in `~/.fzf`.

My main motivation is that I would prefer to install in `~/.config`. The current support for this is broken, as `fzf-settings.zsh` only sources from `~/.fzf`. In addition, the scripts only installs in `~/.config` when `~/.config/fzf` is present, but this requires users deliberately creating this directory, and no one would know since there is no documentation for this.

As an alternative, I have [another branch](https://github.com/caojoshua/fzf-zsh-plugin/tree/config) where I implemented installing in `~/.config` by default. Not sure if this is a good idea though, because it will change the install locations for current users and may be breaking.

# Checklist

- [x] All new and existing tests pass.
- [x] Rather than adding functions to `fzf-zsh-plugin.zsh`, I have created standalone scripts in bin so they can be used by non-ZSH users too.
- [x] Any scripts added use `#!/usr/bin/env interpreter` instead of potentially platform-specific direct paths (`#!/bin/sh` is an ok exception)
- [x] Scripts are marked executable
- [x] Scripts _do not_ have a language file extension unless they are meant to be sourced and not run standalone. No one should have to know if a script was written in bash, python, ruby or whatever. Not including file extensions makes it easier to rewrite the script in another language later without having to change every reference to the previous version.
- [x] I have confirmed that the link(s) in my PR are valid.
- [x] I have read the **CONTRIBUTING** document.

# License Acceptance

- [x] This repository is Apache version 2.0 licensed (some scripts may have alternate licensing inline in their code) and by making this PR, I am contributing my changes to the repository under the terms of the Apache 2 license.

### CODE REVIEW

**Comment by unixorn** [comment]
Maybe have it read `~/.fzf-zsh-plugin.conf` if present and use the contents of that as the directory? Passing the directory as an argument won't work with most frameworks.

**Comment by caojoshua** [comment]
The motivation for a custom installation directory is to avoid adding more entries to `~/`, so I would not want to add another config file there.

I added a change where we can set an environment variable. I think this is cleaner, since there are other environment variables that are being used, and it should work with any framework.

**Review by unixorn — APPROVED** [review]
lgtm.

**Comment by unixorn** [comment]
> The motivation for a custom installation directory is to avoid adding more entries to `~/`, so I would not want to add another config file there.

Fair enough.

> I added a change where we can set an environment variable. I think this is cleaner, since there are other environment variables that are being used, and it should work with any framework.

That works too. People already have to customize their `~/.zshrc` to cope with whatever framework they're using, so it isn't too much extra work

**Pull request merged**
